// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: internal/proto/transfer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      int64                  `protobuf:"varint,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DestinationId int64                  `protobuf:"varint,2,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_internal_proto_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *TransferRequest) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *TransferRequest) GetDestinationId() int64 {
	if x != nil {
		return x.DestinationId
	}
	return 0
}

func (x *TransferRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type TransferResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TransactionId    int64                  `protobuf:"varint,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AuditId          int64                  `protobuf:"varint,3,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	NewSourceBalance string                 `protobuf:"bytes,4,opt,name=new_source_balance,json=newSourceBalance,proto3" json:"new_source_balance,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_internal_proto_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *TransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferResponse) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *TransferResponse) GetAuditId() int64 {
	if x != nil {
		return x.AuditId
	}
	return 0
}

func (x *TransferResponse) GetNewSourceBalance() string {
	if x != nil {
		return x.NewSourceBalance
	}
	return ""
}

var File_internal_proto_transfer_proto protoreflect.FileDescriptor

const file_internal_proto_transfer_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/proto/transfer.proto\x12\btransfer\"m\n" +
	"\x0fTransferRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\x03R\bsourceId\x12%\n" +
	"\x0edestination_id\x18\x02 \x01(\x03R\rdestinationId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"\x9c\x01\n" +
	"\x10TransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\x03R\rtransactionId\x12\x19\n" +
	"\baudit_id\x18\x03 \x01(\x03R\aauditId\x12,\n" +
	"\x12new_source_balance\x18\x04 \x01(\tR\x10newSourceBalance2X\n" +
	"\x0fTransferService\x12E\n" +
	"\fMakeTransfer\x12\x19.transfer.TransferRequest\x1a\x1a.transfer.TransferResponseB)Z'account-transfer-project/internal/protob\x06proto3"

var (
	file_internal_proto_transfer_proto_rawDescOnce sync.Once
	file_internal_proto_transfer_proto_rawDescData []byte
)

func file_internal_proto_transfer_proto_rawDescGZIP() []byte {
	file_internal_proto_transfer_proto_rawDescOnce.Do(func() {
		file_internal_proto_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_transfer_proto_rawDesc), len(file_internal_proto_transfer_proto_rawDesc)))
	})
	return file_internal_proto_transfer_proto_rawDescData
}

var file_internal_proto_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_transfer_proto_goTypes = []any{
	(*TransferRequest)(nil),  // 0: transfer.TransferRequest
	(*TransferResponse)(nil), // 1: transfer.TransferResponse
}
var file_internal_proto_transfer_proto_depIdxs = []int32{
	0, // 0: transfer.TransferService.MakeTransfer:input_type -> transfer.TransferRequest
	1, // 1: transfer.TransferService.MakeTransfer:output_type -> transfer.TransferResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_transfer_proto_init() }
func file_internal_proto_transfer_proto_init() {
	if File_internal_proto_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_transfer_proto_rawDesc), len(file_internal_proto_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_transfer_proto_goTypes,
		DependencyIndexes: file_internal_proto_transfer_proto_depIdxs,
		MessageInfos:      file_internal_proto_transfer_proto_msgTypes,
	}.Build()
	File_internal_proto_transfer_proto = out.File
	file_internal_proto_transfer_proto_goTypes = nil
	file_internal_proto_transfer_proto_depIdxs = nil
}
